// Yalnız SUNUCU public API'si (next/headers'a dokunan veri katmanı). İstemci bileşenleri index.ts'i kullanır.
export {
  getCertificateForAdmin,
  getJobPostingForAdmin,
  getTeamMemberForAdmin,
  listApplicationsForAdmin,
  listCertificatesForAdmin,
  listClientsForAdmin,
  listFaqEntityChoices,
  listFaqsForAdmin,
  listJobPostingsForAdmin,
  listMediaChoices,
  listTeamForAdmin,
  type AdminApplication,
  type AdminCertificate,
  type AdminClient,
  type AdminFaq,
  type AdminJobPosting,
  type AdminTeamMember,
} from './data/adminCorporateRepository';
