-- 0055 · Konfigüratör tanıtım (rehber) sayfaları (K-107): her konfigüratör için SEO odaklı, dizine giren HTML sayfa;
-- iç bağlantı ve "Kendiniz inşa etmek ister misiniz?" bandıyla konfigüratöre yönlendirir. İçerik panelden düzenlenir.
create or replace function app_private.is_content_type(p_type text) returns boolean
language sql immutable as $$
  select p_type in ('service','product','product_category','solution','price_guide','project','project_category','blog_post','static_page','job_posting','configurator_page')
$$;

create table public.configurator_pages (
  id               uuid primary key default gen_random_uuid(),
  configurator_key text not null unique check (configurator_key in ('hall','multi_storey','cladding','mezzanine','fence','drywall')),
  slug             jsonb not null,
  title            jsonb not null,
  hero_summary     jsonb not null default '{}',
  body             jsonb not null default '{}',
  benefits         jsonb not null default '[]' check (jsonb_typeof(benefits) = 'array'),
  steps            jsonb not null default '[]' check (jsonb_typeof(steps) = 'array'),
  faqs             jsonb not null default '[]' check (jsonb_typeof(faqs) = 'array'),
  cta              jsonb not null default '{}',
  cover_image_id   uuid references public.media_library(id) on delete set null,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
call app_private.localized_slug('public.configurator_pages', 'configurator_page');
call app_private.publishable('public.configurator_pages');
call app_private.seo_columns('public.configurator_pages');
call app_private.sortable('public.configurator_pages');
call app_private.track_updated_at('public.configurator_pages');
call app_private.content_policies('public.configurator_pages');
alter table public.configurator_pages add constraint configurator_pages_sizes check (pg_column_size(body) <= 65536 and pg_column_size(faqs) <= 16384);

create function public.get_configurator_page_by_slug(p_locale text, p_slug text) returns jsonb
language sql stable set search_path = '' as $$
  select jsonb_build_object(
    'id', c.id,
    'configurator_key', c.configurator_key,
    'slug', c.slug->>p_locale,
    'title', c.title->>p_locale,
    'hero_summary', c.hero_summary->>p_locale,
    'body', c.body->>p_locale,
    'published_at', c.published_at,
    'updated_at', c.updated_at,
    'benefits', coalesce((select jsonb_agg(jsonb_build_object('title', e->'title'->>p_locale, 'description', e->'description'->>p_locale)) from jsonb_array_elements(c.benefits) e where coalesce(e->'title'->>p_locale, '') <> ''), '[]'::jsonb),
    'steps', coalesce((select jsonb_agg(jsonb_build_object('title', e->'title'->>p_locale, 'description', e->'description'->>p_locale)) from jsonb_array_elements(c.steps) e where coalesce(e->'title'->>p_locale, '') <> ''), '[]'::jsonb),
    'faqs', coalesce((select jsonb_agg(jsonb_build_object('question', e->'question'->>p_locale, 'answer', e->'answer'->>p_locale)) from jsonb_array_elements(c.faqs) e where coalesce(e->'question'->>p_locale, '') <> '' and coalesce(e->'answer'->>p_locale, '') <> ''), '[]'::jsonb),
    'cta', jsonb_build_object('title', c.cta->'title'->>p_locale, 'lead', c.cta->'lead'->>p_locale, 'button', c.cta->'button'->>p_locale),
    'seo', jsonb_build_object('title', c.seo_title->>p_locale, 'description', c.seo_description->>p_locale, 'canonical_url', c.canonical_url, 'noindex', c.noindex,
      'og_image', (select jsonb_build_object('bucket', m.storage_bucket, 'path', m.storage_path, 'width', m.width, 'height', m.height) from public.media_library m where m.id = c.og_image_id)),
    'alternates', jsonb_build_object('tr', case when 'tr' = any(c.published_locales) then c.slug->>'tr' end, 'en', case when 'en' = any(c.published_locales) then c.slug->>'en' end),
    'cover', (select jsonb_build_object('bucket', m.storage_bucket, 'path', m.storage_path, 'width', m.width, 'height', m.height, 'alt', m.alt->>p_locale, 'blur', m.blur_data_url, 'variants', m.variants) from public.media_library m where m.id = c.cover_image_id)
  )
  from public.configurator_pages c
  where c.slug->>p_locale = p_slug and c.status = 'published' and p_locale = any(c.published_locales) and (c.published_at is null or c.published_at <= now())
  limit 1
$$;
revoke execute on function public.get_configurator_page_by_slug(text, text) from public;
grant execute on function public.get_configurator_page_by_slug(text, text) to anon, authenticated;

-- Genel band metni (ürünler/hizmetler sayfalarındaki "Kendiniz inşa etmek ister misiniz?" alanı) — panel: Site Ayarları → Sayfa Metinleri
insert into public.site_settings (key, value, is_public, description) values
('configurator.banner', '{"title": {"tr": "Kendiniz inşa etmek ister misiniz?", "en": "Want to build it yourself?"}, "lead": {"tr": "Yapınızın ölçülerini girin; çelik miktarını, metrajı ve yaklaşık maliyeti anında görün. Sonucu kaydedin, paylaşın ya da teklif isteyin.", "en": "Enter your building''s dimensions; see the steel quantity, take-off and approximate cost instantly. Save, share or request a quote."}, "button": {"tr": "Konfigüratörü aç", "en": "Open the configurator"}}'::jsonb, true, 'Konfigüratör bandı (K-107)')
on conflict (key) do nothing;

-- Başlangıç içeriği: 6 rehber, yalnız TR yayında (EN taslak, onay bekler — K-07). Sayısal iddia/fiyat YOK (K-55).
insert into public.configurator_pages (configurator_key, slug, title, hero_summary, body, benefits, steps, faqs, cta, sort_order, status, published_locales, published_at)
select * from (values
 ('hall', '{"tr":"celik-hol-konfiguratoru","en":"steel-hall-configurator"}'::jsonb, '{"tr":"Çelik Hol Konfigüratörü: Depo ve Fabrika Yapınızı Kendiniz Boyutlandırın","en":"Steel Hall Configurator: Size Your Warehouse or Factory Building Yourself"}'::jsonb,
  '{"tr":"Tek katlı çelik hol, depo, fabrika ve hangar için en, boy, saçak ve mahya yüksekliğini girin; 3B model, eleman listesi ve tonaj anında oluşsun.","en":"Enter width, length, eave and ridge height for a single-storey steel hall, warehouse, factory or hangar; get a 3D model, element list and tonnage instantly."}'::jsonb,
  '{"tr":"## Çelik hol konfigüratörü ne yapar?\n\nÇelik hol konfigüratörü, tek katlı endüstriyel çelik yapılar (depo, fabrika, atölye, hangar) için taşıyıcı sistemi tarayıcıda boyutlandırmanızı sağlar. En, boy, saçak yüksekliği, mahya yüksekliği ve aks aralığını kaydırıcılarla değiştirdikçe 3B model, kolon ve makas sayısı, aşık ve kuşak metrajı ile toplam çelik tonajı anında güncellenir.\n\n## Hangi bilgileri girersiniz?\n\n- **En (açıklık):** çerçevenin serbest açıklığı; geniş açıklıkta sistem otomatik olarak kafes makasa geçer.\n- **Boy ve aks aralığı:** yapının uzunluğu ve çerçeveler arası mesafe; aks aralığı aşık kesitini ve kolon adedini belirler.\n- **Saçak ve mahya yüksekliği:** vinç, raf ya da araç yüksekliği için gereken iç yükseklik ve çatı eğimi.\n- **Görünüm seçenekleri:** aşık ve kuşaklar, kapı boşluğu, sandviç panel kaplama.\n\n## Ne elde edersiniz?\n\nEleman listesi (kolon, makas, aşık, kuşak, çapraz, plaka ve civata), toplam çelik ağırlığı ve kaplama alanı. Üye olarak giriş yaptığınızda güncel malzeme fiyatlarına göre yaklaşık maliyet de görünür. Sonucu kaydedip paylaşım bağlantısıyla ekibinize gönderebilir, yazdırabilir ya da tek tıkla teklif isteyebilirsiniz.\n\nKonfigüratör bir ön boyutlandırma aracıdır; kesin kesitler TBDY 2018''e uygun statik projede belirlenir ve teklif aşamasında yazılı olarak verilir.","en":"## What does the steel hall configurator do?\n\nThe steel hall configurator lets you size the structure of a single-storey industrial steel building (warehouse, factory, workshop, hangar) in the browser. As you move the sliders for width, length, eave height, ridge height and bay spacing, the 3D model, the number of columns and trusses, purlin and girt quantities and the total steel tonnage update instantly.\n\n## What do you enter?\n\n- **Width (span):** the clear span of the frame; at wide spans the system switches to a truss automatically.\n- **Length and bay spacing:** the building length and the distance between frames; bay spacing sets the purlin section and the column count.\n- **Eave and ridge height:** the internal height needed for cranes, racking or vehicles, and the roof pitch.\n- **View options:** purlins and girts, door opening, sandwich panel cladding.\n\n## What do you get?\n\nAn element list (columns, trusses, purlins, girts, bracing, plates and bolts), the total steel weight and the cladding area. Signed-in members also see an approximate cost based on current material prices. Save the result, share it with your team by link, print it or request a quote with one click.\n\nThe configurator is a preliminary sizing tool; final sections are set in the structural design to TBDY 2018 and given in writing at the quotation stage."}'::jsonb,
  '[{"title":{"tr":"Anında 3B model","en":"Instant 3D model"},"description":{"tr":"Her değişiklikte çerçeve, makas ve aşıklar üç boyutlu olarak yeniden çizilir.","en":"Frames, trusses and purlins are redrawn in 3D with every change."}},{"title":{"tr":"Eleman listesi ve tonaj","en":"Element list and tonnage"},"description":{"tr":"Kolon, makas, aşık, kuşak, çapraz ve bağlantı elemanları adet ve ağırlıkla listelenir.","en":"Columns, trusses, purlins, girts, bracing and connections are listed with counts and weights."}},{"title":{"tr":"Kaydet, paylaş, yazdır","en":"Save, share, print"},"description":{"tr":"Paylaşım bağlantısı ve yazdırılabilir özet; teklif formuna tek tıkla aktarım.","en":"Share link and printable summary; one-click transfer to the quote form."}}]'::jsonb,
  '[{"title":{"tr":"Ölçüleri girin","en":"Enter the dimensions"},"description":{"tr":"En, boy, saçak ve mahya yüksekliği, aks aralığı.","en":"Width, length, eave and ridge height, bay spacing."}},{"title":{"tr":"Sonucu inceleyin","en":"Review the result"},"description":{"tr":"3B model, eleman listesi ve tonaj.","en":"3D model, element list and tonnage."}},{"title":{"tr":"Kaydedin ya da teklif isteyin","en":"Save or request a quote"},"description":{"tr":"Bağlantıyı paylaşın, yazdırın ya da teklif formuna aktarın.","en":"Share the link, print, or send it to the quote form."}}]'::jsonb,
  '[{"question":{"tr":"Konfigüratör sonucu kesin fiyat mıdır?","en":"Is the configurator result a firm price?"},"answer":{"tr":"Hayır. Ön boyutlandırma ve yaklaşık maliyet verir; kesin teklif statik proje ve keşif sonrası yazılı olarak hazırlanır.","en":"No. It gives preliminary sizing and an approximate cost; a firm quote is prepared in writing after the structural design and survey."}},{"question":{"tr":"Vinç yolu ya da asma kat ekleyebilir miyim?","en":"Can I add a crane runway or a mezzanine?"},"answer":{"tr":"Hol konfigüratörü ana çerçeveyi boyutlandırır; vinç yolu ve asma kat teklif aşamasında projeye eklenir. Ara kat için ayrı bir konfigüratör vardır.","en":"The hall configurator sizes the main frame; crane runways and mezzanines are added to the design at the quotation stage. There is a separate mezzanine configurator."}},{"question":{"tr":"Sonucu ekibimle paylaşabilir miyim?","en":"Can I share the result with my team?"},"answer":{"tr":"Evet. Kaydettiğiniz konfigürasyonun paylaşım bağlantısı ve yazdırılabilir özeti vardır.","en":"Yes. A saved configuration has a share link and a printable summary."}}]'::jsonb,
  '{"title":{"tr":"Kendiniz inşa etmek ister misiniz?","en":"Want to build it yourself?"},"lead":{"tr":"Holünüzün ölçülerini girin, çelik tonajını ve eleman listesini anında görün.","en":"Enter your hall dimensions and see the steel tonnage and element list instantly."},"button":{"tr":"Hol konfigüratörünü aç","en":"Open the hall configurator"}}'::jsonb, 1),
 ('multi_storey', '{"tr":"cok-katli-celik-yapi-konfiguratoru","en":"multi-storey-steel-building-configurator"}'::jsonb, '{"tr":"Çok Katlı Çelik Yapı Konfigüratörü: Ofis ve Konut Karkasınızı Planlayın","en":"Multi-Storey Steel Building Configurator: Plan Your Office or Residential Frame"}'::jsonb,
  '{"tr":"Kat sayısı, kat yüksekliği, en ve boyu girin; kolon-kiriş çerçeve, aks ızgarası, radye kalınlığı ve çelik tonajı anında hesaplansın.","en":"Enter the number of storeys, storey height, width and length; get the column-beam frame, grid, raft thickness and steel tonnage instantly."}'::jsonb,
  '{"tr":"## Çok katlı çelik yapı konfigüratörü ne yapar?\n\nOfis, konut ve ticari binalar için kolon-kiriş çerçeveyi kat sayısına göre boyutlandırır. En, boy, kat yüksekliği ve kat adedini girdiğinizde aks aralığı, kolon adedi, kiriş kesitleri ve radye temel kalınlığı hesaplanır; 3B model katları ve çerçeveyi gösterir.\n\n## Kentsel dönüşümde neden işe yarar?\n\nDar parselde yeniden yapım planlarken parsel ölçülerini girip kat sayısına göre tonajı görmek, betonarme ile karşılaştırma ve ön bütçe için hızlı bir başlangıç sağlar. Sonucu kaydedip statik proje görüşmesine getirebilirsiniz.\n\n## Ne elde edersiniz?\n\nKat başına kolon ve kiriş listesi, toplam çelik ağırlığı, döşeme alanı ve üye girişiyle yaklaşık maliyet. Paylaşım bağlantısı, yazdırma ve teklif formuna aktarım hol konfigüratörüyle aynıdır.\n\nKesin kesitler ve deprem hesabı TBDY 2018''e göre statik projede yapılır; konfigüratör ön boyutlandırma amaçlıdır.","en":"## What does the multi-storey configurator do?\n\nIt sizes the column-beam frame of office, residential and commercial buildings by the number of storeys. Enter width, length, storey height and storey count; bay spacing, column count, beam sections and raft foundation thickness are calculated and the 3D model shows the storeys and frame.\n\n## Why is it useful for urban renewal?\n\nWhen planning a rebuild on a narrow plot, entering the plot dimensions and seeing the tonnage by storey count gives a quick start for comparison with concrete and a preliminary budget. Save the result and bring it to the structural design meeting.\n\n## What do you get?\n\nA column and beam list per storey, total steel weight, floor area and, when signed in, an approximate cost. Share link, print and transfer to the quote form work as in the hall configurator.\n\nFinal sections and the seismic design are done in the structural design to TBDY 2018; the configurator is for preliminary sizing."}'::jsonb,
  '[{"title":{"tr":"Kat sayısına göre çerçeve","en":"Frame by storey count"},"description":{"tr":"Aks aralığı, kolon adedi ve kiriş kesitleri kat sayısıyla birlikte hesaplanır.","en":"Bay spacing, column count and beam sections are calculated with the storey count."}},{"title":{"tr":"Radye temel kalınlığı","en":"Raft foundation thickness"},"description":{"tr":"Yapı yüküne göre önerilen radye kalınlığı görünür.","en":"A suggested raft thickness appears for the building load."}},{"title":{"tr":"Betonarmeyle karşılaştırma için hızlı tonaj","en":"Quick tonnage to compare with concrete"},"description":{"tr":"Kentsel dönüşüm ön bütçesi için çelik tonajı dakikalar içinde.","en":"Steel tonnage in minutes for an urban-renewal preliminary budget."}}]'::jsonb,
  '[{"title":{"tr":"Parsel ve kat bilgisini girin","en":"Enter plot and storey data"},"description":{"tr":"En, boy, kat yüksekliği, kat adedi.","en":"Width, length, storey height, storey count."}},{"title":{"tr":"Çerçeveyi inceleyin","en":"Review the frame"},"description":{"tr":"3B model, kolon-kiriş listesi, radye kalınlığı.","en":"3D model, column-beam list, raft thickness."}},{"title":{"tr":"Kaydedin ya da teklif isteyin","en":"Save or request a quote"},"description":{"tr":"Bağlantıyı paylaşın ya da teklif formuna aktarın.","en":"Share the link or send it to the quote form."}}]'::jsonb,
  '[{"question":{"tr":"Kaç kata kadar hesaplıyor?","en":"How many storeys does it handle?"},"answer":{"tr":"Konfigüratör kural setinde tanımlı kat aralığında çalışır; daha yüksek yapılar için teklif formundan ulaşın.","en":"It works within the storey range defined in the rule set; for taller buildings contact us through the quote form."}},{"question":{"tr":"Asansör ve merdiven kovası dahil mi?","en":"Are lift and stair shafts included?"},"answer":{"tr":"Ön boyutlandırmada dahil değildir; mimari projeyle birlikte statik projede ele alınır.","en":"Not in the preliminary sizing; they are handled in the structural design together with the architectural plan."}}]'::jsonb,
  '{"title":{"tr":"Kendiniz inşa etmek ister misiniz?","en":"Want to build it yourself?"},"lead":{"tr":"Parsel ölçülerinizi ve kat sayısını girin; çelik karkasın tonajını anında görün.","en":"Enter your plot dimensions and storey count; see the frame tonnage instantly."},"button":{"tr":"Çok katlı konfigüratörü aç","en":"Open the multi-storey configurator"}}'::jsonb, 2),
 ('cladding', '{"tr":"cati-ve-cephe-kaplama-konfiguratoru","en":"roof-and-facade-cladding-configurator"}'::jsonb, '{"tr":"Çatı ve Cephe Kaplama Konfigüratörü: Trapez Sac ve Sandviç Panel Metrajı","en":"Roof and Facade Cladding Configurator: Trapezoidal Sheet and Sandwich Panel Take-Off"}'::jsonb,
  '{"tr":"Beşik çatı ve cephe için levha adedi, m², ağırlık, vida, mahya ve oluk metrajını girdiğiniz ölçülerden hesaplayın; kalemleri teklif sepetine ekleyin.","en":"Calculate sheet count, m², weight, screws, ridge and gutter quantities for a gable roof and facade from your dimensions; add the items to the quote basket."}'::jsonb,
  '{"tr":"## Kaplama konfigüratörü ne yapar?\n\nBeşik çatılı bir yapının çatı ve cephe kaplamasını metrajlar. En, boy, çatı eğimi ve duvar yüksekliğini girin; çatı ve cephe alanı, seçtiğiniz malzemeye (trapez sac ya da sandviç panel) göre levha adedi, toplam ağırlık, vida, mahya ve oluk uzunluğu hesaplanır.\n\n## Kimler için?\n\nMevcut bir çelik yapının kaplamasını yenileyecekler, yeni depo veya atölye için malzeme listesi çıkaracaklar ve teklif öncesi bütçe kurmak isteyenler için. Sonuçtaki kalemler ürün kataloğumuzdaki gerçek ürünlere bağlıdır ve tek tıkla teklif sepetine eklenir.\n\n## Ne elde edersiniz?\n\nÇatı ve cephe için ayrı ayrı m², levha adedi ve ağırlık; aksesuar metrajı; 2B kesit şeması ve 3B görünüm. Bağlantıyı paylaşabilir, sepete ekleyip teklif isteyebilirsiniz.","en":"## What does the cladding configurator do?\n\nIt takes off the roof and facade cladding of a gable-roof building. Enter width, length, roof pitch and wall height; roof and facade areas, sheet count for the chosen material (trapezoidal sheet or sandwich panel), total weight, screws, ridge and gutter lengths are calculated.\n\n## Who is it for?\n\nThose renewing the cladding of an existing steel building, preparing a material list for a new warehouse or workshop, or building a budget before a quote. The items in the result are linked to real products in our catalogue and can be added to the quote basket with one click.\n\n## What do you get?\n\nSeparate m², sheet count and weight for roof and facade; accessory quantities; a 2D section diagram and a 3D view. Share the link, add to the basket and request a quote."}'::jsonb,
  '[{"title":{"tr":"Malzemeye göre levha adedi","en":"Sheet count by material"},"description":{"tr":"Trapez sac ya da sandviç panel; levha boyuna göre adet ve fire.","en":"Trapezoidal sheet or sandwich panel; count and waste by sheet length."}},{"title":{"tr":"Aksesuar metrajı","en":"Accessory take-off"},"description":{"tr":"Vida, mahya ve oluk uzunluğu otomatik.","en":"Screws, ridge and gutter lengths automatically."}},{"title":{"tr":"Sepete tek tıkla","en":"One click to the basket"},"description":{"tr":"Kalemler kataloğa bağlıdır; teklif sepetine eklenir.","en":"Items are linked to the catalogue and added to the quote basket."}}]'::jsonb,
  '[{"title":{"tr":"Yapı ölçülerini girin","en":"Enter the building dimensions"},"description":{"tr":"En, boy, eğim, duvar yüksekliği.","en":"Width, length, pitch, wall height."}},{"title":{"tr":"Malzemeyi seçin","en":"Choose the material"},"description":{"tr":"Çatı ve cephe için trapez sac ya da sandviç panel.","en":"Trapezoidal sheet or sandwich panel for roof and facade."}},{"title":{"tr":"Sepete ekleyin","en":"Add to the basket"},"description":{"tr":"Kalemleri teklif sepetine aktarın, teklif isteyin.","en":"Send the items to the quote basket and request a quote."}}]'::jsonb,
  '[{"question":{"tr":"Fire payı hesaba dahil mi?","en":"Is waste included?"},"answer":{"tr":"Levha boyuna göre kesim ve bindirme payı kural setinde tanımlıdır; kesin liste teklif aşamasında netleşir.","en":"Cutting and overlap allowances by sheet length are defined in the rule set; the final list is confirmed at the quotation stage."}},{"question":{"tr":"Kırma çatı için kullanılabilir mi?","en":"Can it be used for a hipped roof?"},"answer":{"tr":"Konfigüratör beşik çatı içindir; kırma çatı ve özel formlar için teklif formundan ölçülerinizi iletin.","en":"The configurator is for gable roofs; for hipped roofs and special shapes send your dimensions through the quote form."}}]'::jsonb,
  '{"title":{"tr":"Kendiniz inşa etmek ister misiniz?","en":"Want to build it yourself?"},"lead":{"tr":"Çatı ve cephe ölçülerinizi girin; levha adedini ve ağırlığı anında görün.","en":"Enter your roof and facade dimensions; see sheet count and weight instantly."},"button":{"tr":"Kaplama konfigüratörünü aç","en":"Open the cladding configurator"}}'::jsonb, 3),
 ('mezzanine', '{"tr":"ara-kat-platformu-konfiguratoru","en":"mezzanine-platform-configurator"}'::jsonb, '{"tr":"Ara Kat Platformu Konfigüratörü: Depo İçi Çelik Asma Kat Metrajı","en":"Mezzanine Platform Configurator: Steel Mezzanine Take-Off for Warehouses"}'::jsonb,
  '{"tr":"Depo ve atölye içine çelik ara kat: en, boy, yükseklik ve kolon aralığını girin; kolon ızgarası, ana ve tali kirişler, döşeme sacı, merdiven ve korkuluk metrajı çıksın.","en":"A steel mezzanine inside a warehouse or workshop: enter width, length, height and column spacing; get the column grid, primary and secondary beams, deck sheet, stair and railing quantities."}'::jsonb,
  '{"tr":"## Ara kat konfigüratörü ne yapar?\n\nMevcut bir depo ya da atölyenin içine kurulacak çelik ara kat platformunu boyutlandırır. Platform ölçüleri, yükseklik ve kolon aralığına göre kolon ızgarası, ana ve tali kirişler, döşeme sacı ve beton, merdiven ile korkuluk metrajı hesaplanır; 3B model platformu içinde gösterir.\n\n## Nerede kullanılır?\n\nDepolarda raf ya da ofis alanı kazanmak, atölyelerde mezanin kat oluşturmak, mağaza ve showroomlarda ek kat açmak için. Yükleme sınıfına göre kesitler kural setinden gelir.\n\n## Ne elde edersiniz?\n\nEleman listesi, toplam çelik ağırlığı, döşeme alanı ve merdiven-korkuluk uzunlukları; paylaşım bağlantısı ve teklif sepetine aktarım.","en":"## What does the mezzanine configurator do?\n\nIt sizes a steel mezzanine platform to be installed inside an existing warehouse or workshop. From the platform dimensions, height and column spacing it calculates the column grid, primary and secondary beams, deck sheet and concrete, stair and railing quantities; the 3D model shows the platform.\n\n## Where is it used?\n\nTo gain racking or office space in warehouses, create a mezzanine floor in workshops, or add a level in shops and showrooms. Sections come from the rule set by load class.\n\n## What do you get?\n\nAn element list, total steel weight, floor area and stair/railing lengths; a share link and transfer to the quote basket."}'::jsonb,
  '[{"title":{"tr":"Kolon ızgarası ve kirişler","en":"Column grid and beams"},"description":{"tr":"Kolon aralığına göre ana ve tali kiriş kesitleri.","en":"Primary and secondary beam sections by column spacing."}},{"title":{"tr":"Döşeme, merdiven, korkuluk","en":"Deck, stair, railing"},"description":{"tr":"Döşeme sacı ve beton, merdiven ve korkuluk metrajı birlikte.","en":"Deck sheet and concrete, stair and railing quantities together."}},{"title":{"tr":"Mevcut yapıya uyum","en":"Fits the existing building"},"description":{"tr":"Yükseklik ve kolon aralığını mevcut düzene göre seçin.","en":"Choose height and column spacing to suit the existing layout."}}]'::jsonb,
  '[{"title":{"tr":"Platform ölçülerini girin","en":"Enter the platform dimensions"},"description":{"tr":"En, boy, yükseklik, kolon aralığı.","en":"Width, length, height, column spacing."}},{"title":{"tr":"Metrajı inceleyin","en":"Review the take-off"},"description":{"tr":"Kolon, kiriş, döşeme, merdiven ve korkuluk.","en":"Columns, beams, deck, stair and railing."}},{"title":{"tr":"Teklif isteyin","en":"Request a quote"},"description":{"tr":"Kalemleri sepete ekleyin ya da bağlantıyı paylaşın.","en":"Add the items to the basket or share the link."}}]'::jsonb,
  '[{"question":{"tr":"Mevcut zemin ara katı taşır mı?","en":"Will the existing floor carry a mezzanine?"},"answer":{"tr":"Kolon yükleri sonuçta görünür; zemin kontrolü keşifte yapılır ve gerekirse temel plakası büyütülür.","en":"Column loads appear in the result; the floor is checked at the survey and base plates enlarged if needed."}},{"question":{"tr":"Forklift yükü için uygun mu?","en":"Is it suitable for forklift loads?"},"answer":{"tr":"Konfigüratör yükleme sınıfına göre kesit seçer; ağır yükler için teklif aşamasında ayrıca değerlendirilir.","en":"The configurator selects sections by load class; heavy loads are assessed separately at the quotation stage."}}]'::jsonb,
  '{"title":{"tr":"Kendiniz inşa etmek ister misiniz?","en":"Want to build it yourself?"},"lead":{"tr":"Ara kat ölçülerinizi girin; kolon, kiriş ve döşeme metrajını anında görün.","en":"Enter your mezzanine dimensions; see column, beam and deck quantities instantly."},"button":{"tr":"Ara kat konfigüratörünü aç","en":"Open the mezzanine configurator"}}'::jsonb, 4),
 ('fence', '{"tr":"cit-ve-korkuluk-konfiguratoru","en":"fence-and-railing-configurator"}'::jsonb, '{"tr":"Çit ve Korkuluk Konfigüratörü: Direk, Kutu Profil ve Panel Metrajı","en":"Fence and Railing Configurator: Post, Box Section and Panel Take-Off"}'::jsonb,
  '{"tr":"Bahçe çiti, çevre duvarı üstü korkuluk ve sanayi çiti için uzunluk, yükseklik ve direk aralığını girin; direk, yatay profil, panel ve ankraj metrajı hazır olsun.","en":"For garden fences, wall-top railings and industrial fencing enter length, height and post spacing; get post, rail, panel and anchor quantities."}'::jsonb,
  '{"tr":"## Çit ve korkuluk konfigüratörü ne yapar?\n\nToplam uzunluk, yükseklik ve direk aralığını girdiğinizde direk adedi, yatay kutu profil metrajı, panel ya da dolgu adedi, kapı boşluğu ve ankraj/plaka sayısı hesaplanır. 3B görünüm çiti direkleriyle birlikte gösterir; kalemler ürün kataloğundaki kutu profillere bağlıdır.\n\n## Kimler için?\n\nBahçe ve site çevre çiti, teras ve merdiven korkuluğu, fabrika sahası çiti planlayanlar için. Metraj çıktısı doğrudan teklif sepetine eklenir.\n\n## Ne elde edersiniz?\n\nDirek, yatay profil ve dolgu listesi, toplam ağırlık, boya/galvaniz yüzeyi için alan bilgisi; paylaşım bağlantısı ve teklif isteği.","en":"## What does the fence and railing configurator do?\n\nEnter total length, height and post spacing; post count, horizontal box-section length, panel or infill count, gate opening and anchor/plate count are calculated. The 3D view shows the fence with its posts; the items are linked to the box sections in the product catalogue.\n\n## Who is it for?\n\nThose planning garden and estate perimeter fences, terrace and stair railings, or factory-site fencing. The take-off goes straight to the quote basket.\n\n## What do you get?\n\nA post, rail and infill list, total weight, surface area for paint or galvanising; share link and quote request."}'::jsonb,
  '[{"title":{"tr":"Direk ve profil adedi","en":"Post and rail counts"},"description":{"tr":"Direk aralığına göre direk, yatay profil ve dolgu adedi.","en":"Posts, rails and infill by post spacing."}},{"title":{"tr":"Kapı ve ankraj","en":"Gate and anchors"},"description":{"tr":"Kapı boşluğu düşülür; plaka ve ankraj sayısı eklenir.","en":"Gate opening deducted; plate and anchor counts added."}},{"title":{"tr":"Kataloğa bağlı kalemler","en":"Catalogue-linked items"},"description":{"tr":"Kutu profiller gerçek ölçülerle sepete girer.","en":"Box sections go to the basket with real sizes."}}]'::jsonb,
  '[{"title":{"tr":"Uzunluk ve yüksekliği girin","en":"Enter length and height"},"description":{"tr":"Toplam uzunluk, yükseklik, direk aralığı, kapı.","en":"Total length, height, post spacing, gate."}},{"title":{"tr":"Metrajı inceleyin","en":"Review the take-off"},"description":{"tr":"Direk, profil, dolgu, ankraj.","en":"Posts, rails, infill, anchors."}},{"title":{"tr":"Sepete ekleyin","en":"Add to the basket"},"description":{"tr":"Teklif isteyin ya da bağlantıyı paylaşın.","en":"Request a quote or share the link."}}]'::jsonb,
  '[{"question":{"tr":"Eğimli arazide çalışır mı?","en":"Does it work on sloping ground?"},"answer":{"tr":"Metraj düz hat üzerinden hesaplanır; eğim ve kademeler keşifte netleştirilir.","en":"The take-off is for a straight run; slopes and steps are confirmed at the survey."}},{"question":{"tr":"Galvaniz ya da boya seçebilir miyim?","en":"Can I choose galvanised or painted?"},"answer":{"tr":"Yüzey işlemi teklif aşamasında seçilir; konfigüratör metrajı ve ağırlığı verir.","en":"Surface treatment is chosen at the quotation stage; the configurator gives quantities and weight."}}]'::jsonb,
  '{"title":{"tr":"Kendiniz inşa etmek ister misiniz?","en":"Want to build it yourself?"},"lead":{"tr":"Çit uzunluğunu ve yüksekliğini girin; direk ve profil metrajını anında görün.","en":"Enter the fence length and height; see post and rail quantities instantly."},"button":{"tr":"Çit konfigüratörünü aç","en":"Open the fence configurator"}}'::jsonb, 5),
 ('drywall', '{"tr":"alcipan-bolme-duvar-konfiguratoru","en":"drywall-partition-configurator"}'::jsonb, '{"tr":"Alçıpan Bölme Duvar Konfigüratörü: Levha, Profil ve Vida Metrajı","en":"Drywall Partition Configurator: Board, Stud and Screw Take-Off"}'::jsonb,
  '{"tr":"Duvar uzunluğu, yüksekliği ve katman sayısını girin; alçıpan levha, kutu profil dikme, yalıtım ve vida adedi anında hesaplansın.","en":"Enter wall length, height and layer count; get plasterboard sheets, box-section studs, insulation and screw counts instantly."}'::jsonb,
  '{"tr":"## Alçıpan bölme duvar konfigüratörü ne yapar?\n\nKutu profil taşıyıcılı alçıpan bölme duvar için malzeme listesi çıkarır. Duvar uzunluğu, yüksekliği, dikme aralığı ve levha katman sayısını girdiğinizde levha adedi, dikme ve ray profili metrajı, yalıtım alanı, vida ve derz bandı miktarı hesaplanır; 3B görünüm duvar iskeletini gösterir.\n\n## Kimler için?\n\nOfis bölmeleri, konut iç duvarları, mağaza ve depo içi ayırıcı duvarlar planlayanlar için. Kalemler kataloğumuzdaki kutu profil ve alçıpan ürünlerine bağlıdır.\n\n## Ne elde edersiniz?\n\nLevha, profil, yalıtım ve sarf malzemesi listesi, toplam ağırlık ve duvar alanı; sepete ekleme, paylaşım ve teklif isteği.","en":"## What does the drywall partition configurator do?\n\nIt produces a material list for plasterboard partitions on box-section studs. Enter wall length, height, stud spacing and number of board layers; sheet count, stud and track lengths, insulation area, screw and joint tape quantities are calculated and the 3D view shows the wall frame.\n\n## Who is it for?\n\nThose planning office partitions, residential internal walls, or dividing walls in shops and warehouses. Items are linked to the box-section and plasterboard products in our catalogue.\n\n## What do you get?\n\nA board, stud, insulation and consumables list, total weight and wall area; add to basket, share and quote request."}'::jsonb,
  '[{"title":{"tr":"Levha ve dikme adedi","en":"Board and stud counts"},"description":{"tr":"Dikme aralığı ve katman sayısına göre levha ve profil metrajı.","en":"Board and section quantities by stud spacing and layer count."}},{"title":{"tr":"Sarf malzemesi","en":"Consumables"},"description":{"tr":"Vida, derz bandı ve yalıtım alanı otomatik.","en":"Screws, joint tape and insulation area automatically."}},{"title":{"tr":"Kataloğa bağlı","en":"Catalogue-linked"},"description":{"tr":"Kutu profil ve levhalar gerçek ürünlerle sepete girer.","en":"Box sections and boards go to the basket as real products."}}]'::jsonb,
  '[{"title":{"tr":"Duvar ölçülerini girin","en":"Enter the wall dimensions"},"description":{"tr":"Uzunluk, yükseklik, dikme aralığı, katman.","en":"Length, height, stud spacing, layers."}},{"title":{"tr":"Listeyi inceleyin","en":"Review the list"},"description":{"tr":"Levha, profil, yalıtım, sarf.","en":"Boards, sections, insulation, consumables."}},{"title":{"tr":"Sepete ekleyin","en":"Add to the basket"},"description":{"tr":"Teklif isteyin ya da bağlantıyı paylaşın.","en":"Request a quote or share the link."}}]'::jsonb,
  '[{"question":{"tr":"Kapı boşluğu düşülüyor mu?","en":"Are door openings deducted?"},"answer":{"tr":"Kapı adedi ve ölçüsü girildiğinde levha ve profil metrajından düşülür.","en":"When door count and size are entered they are deducted from board and section quantities."}},{"question":{"tr":"Ses yalıtımı için hangi katman?","en":"Which layers for acoustic insulation?"},"answer":{"tr":"Çift katman levha ve taş yünü seçeneği kural setinde vardır; ihtiyaca göre teklif aşamasında netleştirilir.","en":"Double-layer boards and stone wool are available in the rule set; the choice is confirmed at the quotation stage."}}]'::jsonb,
  '{"title":{"tr":"Kendiniz inşa etmek ister misiniz?","en":"Want to build it yourself?"},"lead":{"tr":"Duvar ölçülerinizi girin; levha, profil ve vida adedini anında görün.","en":"Enter your wall dimensions; see board, stud and screw counts instantly."},"button":{"tr":"Alçıpan konfigüratörünü aç","en":"Open the drywall configurator"}}'::jsonb, 6)
) as v(configurator_key, slug, title, hero_summary, body, benefits, steps, faqs, cta, sort_order)
cross join lateral (select 'published'::text, '{tr}'::text[], now()) as p(status, published_locales, published_at)
where not exists (select 1 from public.configurator_pages x where x.configurator_key = v.configurator_key);
